name: Test
on:
  - push
  - pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          cache: "node"
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm run test -- --run
